### ISSUE TITLE
emi (the mod) incompat (1.20.1 forge)

### ISSUE THREAD

**Issue by No1129** [Thelnfamous1/Combat-Next#3]
```
[17:09:53] [Thread-41/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Method net/minecraft/world/level/block/CarvedPumpkinBlock.m_40402_()Lnet/minecraft/world/entity/EquipmentSlot; is abstract
	Index: 1
	Listeners:
		0: HIGHEST
		1: ASM: class com.infamous.combat_next.ForgeEventHandler onAttributeModification(Lnet/minecraftforge/event/ItemAttributeModifierEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1923/0x0000000801471148@13cbaa79
		4: net.minecraftforge.eventbus.EventBus$$Lambda$1923/0x0000000801471148@5b1fc60b
		5: ASM: class net.mcreator.enlightened_end.procedures.SpecialattributeProcedure addAttributeModifier(Lnet/minecraftforge/event/ItemAttributeModifierEvent;)V
java.lang.AbstractMethodError: Method net/minecraft/world/level/block/CarvedPumpkinBlock.m_40402_()Lnet/minecraft/world/entity/EquipmentSlot; is abstract
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.CarvedPumpkinBlock.m_40402_(CarvedPumpkinBlock.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_147233_(LivingEntity.java:3391)
	at TRANSFORMER/combat_next@1.20.1-1.0.0/com.infamous.combat_next.ForgeEventHandler.onAttributeModification(ForgeEventHandler.java:54)
	at TRANSFORMER/combat_next@1.20.1-1.0.0/com.infamous.combat_next.__ForgeEventHandler_onAttributeModification_ItemAttributeModifierEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:959)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:890)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:674)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.api.stack.ItemEmiStack.getTooltipText(ItemEmiStack.java:140)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.search.EmiSearch.bake(EmiSearch.java:59)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:203)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:09:53] [Thread-41/ERROR] [EMI/]: [EMI] Critical error occured during reload:
java.lang.AbstractMethodError: Method net/minecraft/world/level/block/CarvedPumpkinBlock.m_40402_()Lnet/minecraft/world/entity/EquipmentSlot; is abstract
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.CarvedPumpkinBlock.m_40402_(CarvedPumpkinBlock.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_147233_(LivingEntity.java:3391)
	at TRANSFORMER/combat_next@1.20.1-1.0.0/com.infamous.combat_next.ForgeEventHandler.onAttributeModification(ForgeEventHandler.java:54)
	at TRANSFORMER/combat_next@1.20.1-1.0.0/com.infamous.combat_next.__ForgeEventHandler_onAttributeModification_ItemAttributeModifierEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:959)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:890)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:674)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.api.stack.ItemEmiStack.getTooltipText(ItemEmiStack.java:140)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.search.EmiSearch.bake(EmiSearch.java:59)
	at TRANSFORMER/emi@1.0.22+1.20.1+forge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:203)
```
this makes emi fail to load
1.20.1 forge

**Comment by Thelnfamous1** [comment]
I've shared this error with other developers, and to put it simply, they remarked that there are shenanigans going on. Report this to EMI's github if you haven't already and cross-link this issue.
